-- test normal hue-saturation-lightness values

texturemodifiertest.create_node("contrast", nil,  96)
texturemodifiertest.create_node("contrast", nil,  64)
texturemodifiertest.create_node("contrast", nil,  32)
texturemodifiertest.create_node("contrast", nil,   0)
texturemodifiertest.create_node("contrast", nil, -32)
texturemodifiertest.create_node("contrast", nil, -64)
texturemodifiertest.create_node("contrast", nil, -96)

texturemodifiertest.create_node("contrast", nil,  96, 96)
texturemodifiertest.create_node("contrast", nil,  64, 96)
texturemodifiertest.create_node("contrast", nil,  32, 96)
texturemodifiertest.create_node("contrast", nil,   0, 96)
texturemodifiertest.create_node("contrast", nil, -32, 96)
texturemodifiertest.create_node("contrast", nil, -64, 96)
texturemodifiertest.create_node("contrast", nil, -96, 96)

texturemodifiertest.create_node("contrast", nil,  96, 64)
texturemodifiertest.create_node("contrast", nil,  64, 64)
texturemodifiertest.create_node("contrast", nil,  32, 64)
texturemodifiertest.create_node("contrast", nil,   0, 64)
texturemodifiertest.create_node("contrast", nil, -32, 64)
texturemodifiertest.create_node("contrast", nil, -64, 64)
texturemodifiertest.create_node("contrast", nil, -96, 64)

texturemodifiertest.create_node("contrast", nil,  96, 32)
texturemodifiertest.create_node("contrast", nil,  64, 32)
texturemodifiertest.create_node("contrast", nil,  32, 32)
texturemodifiertest.create_node("contrast", nil,   0, 32)
texturemodifiertest.create_node("contrast", nil, -32, 32)
texturemodifiertest.create_node("contrast", nil, -64, 32)
texturemodifiertest.create_node("contrast", nil, -96, 32)

texturemodifiertest.create_node("contrast", nil,  96, -32)
texturemodifiertest.create_node("contrast", nil,  64, -32)
texturemodifiertest.create_node("contrast", nil,  32, -32)
texturemodifiertest.create_node("contrast", nil,   0, -32)
texturemodifiertest.create_node("contrast", nil, -32, -32)
texturemodifiertest.create_node("contrast", nil, -64, -32)
texturemodifiertest.create_node("contrast", nil, -96, -32)

texturemodifiertest.create_node("contrast", nil,  96, -64)
texturemodifiertest.create_node("contrast", nil,  64, -64)
texturemodifiertest.create_node("contrast", nil,  32, -64)
texturemodifiertest.create_node("contrast", nil,   0, -64)
texturemodifiertest.create_node("contrast", nil, -32, -64)
texturemodifiertest.create_node("contrast", nil, -64, -64)
texturemodifiertest.create_node("contrast", nil, -96, -64)

texturemodifiertest.create_node("contrast", nil,  96, -96)
texturemodifiertest.create_node("contrast", nil,  64, -96)
texturemodifiertest.create_node("contrast", nil,  32, -96)
texturemodifiertest.create_node("contrast", nil,   0, -96)
texturemodifiertest.create_node("contrast", nil, -32, -96)
texturemodifiertest.create_node("contrast", nil, -64, -96)
texturemodifiertest.create_node("contrast", nil, -96, -96)
