-- test the maximum legal values of the texture modifier input range

-- Hue-Saturation-Lightness
texturemodifiertest.create_node("hsl", "extreme", 180)
texturemodifiertest.create_node("hsl", "extreme", 0)
texturemodifiertest.create_node("hsl", "extreme", -180)
texturemodifiertest.create_node("hsl", "extreme", 180, 100, 100)
texturemodifiertest.create_node("hsl", "extreme", 180, 100, 0)
texturemodifiertest.create_node("hsl", "extreme", 180, 100, -100)
texturemodifiertest.create_node("hsl", "extreme", 180, 0, 100)
texturemodifiertest.create_node("hsl", "extreme", 180, 0, 0)
texturemodifiertest.create_node("hsl", "extreme", 180, 0, -100)
texturemodifiertest.create_node("hsl", "extreme", 180, -100, 100)
texturemodifiertest.create_node("hsl", "extreme", 180, -100, 0)
texturemodifiertest.create_node("hsl", "extreme", 180, -100, -100)
texturemodifiertest.create_node("hsl", "extreme", 0, 100, 100)
texturemodifiertest.create_node("hsl", "extreme", 0, 100, 0)
texturemodifiertest.create_node("hsl", "extreme", 0, 100, -100)
texturemodifiertest.create_node("hsl", "extreme", 0, 0, 100)
texturemodifiertest.create_node("hsl", "extreme", 0, 0, 0)
texturemodifiertest.create_node("hsl", "extreme", 0, 0, -100)
texturemodifiertest.create_node("hsl", "extreme", 0, -100, 100)
texturemodifiertest.create_node("hsl", "extreme", 0, -100, 0)
texturemodifiertest.create_node("hsl", "extreme", 0, -100, -100)
texturemodifiertest.create_node("hsl", "extreme", -180, 100, 100)
texturemodifiertest.create_node("hsl", "extreme", -180, 100, 0)
texturemodifiertest.create_node("hsl", "extreme", -180, 100, -100)
texturemodifiertest.create_node("hsl", "extreme", -180, 0, 100)
texturemodifiertest.create_node("hsl", "extreme", -180, 0, 0)
texturemodifiertest.create_node("hsl", "extreme", -180, 0, -100)
texturemodifiertest.create_node("hsl", "extreme", -180, -100, 100)
texturemodifiertest.create_node("hsl", "extreme", -180, -100, 0)
texturemodifiertest.create_node("hsl", "extreme", -180, -100, -100)


-- Colorize
texturemodifiertest.create_node("colorizehsl", "extreme", 180)
texturemodifiertest.create_node("colorizehsl", "extreme", 0)
texturemodifiertest.create_node("colorizehsl", "extreme", -180)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 100, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 0, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 0, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, 0, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, -100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, -100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 180, -100, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 100, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 0, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 0, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, 0, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, -100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, -100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", 0, -100, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 100, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 0, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 0, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, 0, -100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, -100, 100)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, -100, 0)
texturemodifiertest.create_node("colorizehsl", "extreme", -180, -100, -100)

-- Brightness-Contrast
texturemodifiertest.create_node("contrast", "extreme", 127)
texturemodifiertest.create_node("contrast", "extreme", 0)
texturemodifiertest.create_node("contrast", "extreme", -127)
texturemodifiertest.create_node("contrast", "extreme", 127, 127)
texturemodifiertest.create_node("contrast", "extreme", 127, 0)
texturemodifiertest.create_node("contrast", "extreme", 127, -127)
texturemodifiertest.create_node("contrast", "extreme", 0, 127)
texturemodifiertest.create_node("contrast", "extreme", 0, 0)
texturemodifiertest.create_node("contrast", "extreme", 0, -127)
texturemodifiertest.create_node("contrast", "extreme", -127, 127)
texturemodifiertest.create_node("contrast", "extreme", -127, 0)
texturemodifiertest.create_node("contrast", "extreme", -127, -127)

-- Screen
texturemodifiertest.create_node("screen", "extreme", "#FFFFFF")
texturemodifiertest.create_node("screen", "extreme", "#000000")
texturemodifiertest.create_node("screen", "extreme", "#00FF00")
texturemodifiertest.create_node("screen", "extreme", "#FF00FF")

